Repository lambdaclass/lambda_ethereum_consensus, pull requests merged in 2024-03, with the labels that each got.

#790 refactor: deduplicate block downloading and incoming requests handling
  lib/lambda_ethereum_consensus/beacon/beacon_chain.ex
  lib/lambda_ethereum_consensus/p2p/block_downloader.ex
  lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
  lib/lambda_ethereum_consensus/p2p/req_resp.ex
  lib/lambda_ethereum_consensus/p2p/utils.ex
  lib/ssz_ex.ex
  lib/types/p2p/beacon_blocks_by_range_request.ex
  lib/types/p2p/beacon_blocks_by_root_request.ex
  lib/types/p2p/metadata.ex
  lib/types/p2p/status_message.ex
  lib/types/type_aliases.ex
  native/libp2p_port/internal/reqresp/reqresp.go
  test/unit/req_resp_test.exs
Labels: Refactor

#783 feat: subscribe to blob subnets
  lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex
  lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
  lib/lambda_ethereum_consensus/store/blob_db.ex
  lib/types/beacon_chain/execution_payload_deneb.ex
  lib/types/beacon_chain/execution_payload_header.ex
  lib/types/beacon_chain/execution_payload_header_deneb.ex
Labels: deneb

#819 feat: allow dynamically changing node's ENR
  lib/lambda_ethereum_consensus/beacon/beacon_chain.ex
  lib/libp2p_port.ex
  lib/types/p2p/enr_fork_id.ex
  native/libp2p_port/internal/discovery/discovery.go
  native/libp2p_port/internal/proto_helpers/proto_helpers.go
  native/libp2p_port/main.go
  proto/libp2p.proto
  test/unit/beacon_api_test.exs
  test/unit/libp2p_port_test.exs
Labels: validator

#824 feat: add `BlobDownloader`
  lib/lambda_ethereum_consensus/beacon/sync_blocks.ex
  lib/lambda_ethereum_consensus/p2p/blob_downloader.ex
  lib/lambda_ethereum_consensus/p2p/block_downloader.ex
  lib/lambda_ethereum_consensus/p2p/req_resp.ex
  lib/types/p2p/blob_sidecars_by_root_request.ex
  test/unit/req_resp_test.exs
Labels: deneb

#843 fix: encode requests with `encode_request`
  lib/lambda_ethereum_consensus/p2p/blob_downloader.ex
  lib/lambda_ethereum_consensus/p2p/block_downloader.ex
  lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
  lib/types/p2p/beacon_blocks_by_range_response.ex
  lib/types/p2p/beacon_blocks_by_root_request.ex
  lib/types/p2p/beacon_blocks_by_root_response.ex
  lib/types/p2p/blob_sidecars_by_root_request.ex
  lib/types/type_aliases.ex
  native/ssz_nif/src/elx_types/p2p.rs
  native/ssz_nif/src/ssz_types/p2p.rs
  native/ssz_nif/src/utils/mod.rs
  test/unit/req_resp_test.exs
Labels: bug

#842 fix: reduce calls to `get_ancestor` in `get_head`
  lib/lambda_ethereum_consensus/fork_choice/handlers.ex
  lib/lambda_ethereum_consensus/fork_choice/helpers.ex
Labels: bug, perf

#838 feat: produce attestations
  lib/bls.ex
  lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
  lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
  lib/lambda_ethereum_consensus/validator/utils.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  lib/utils/bit_list.ex
Labels: validator, Attester

#850 fix: bugs in Libp2pPort and IncomingRequests.Handler
  config/runtime.exs
  lib/lambda_ethereum_consensus/p2p/incoming_requests/handler.ex
  lib/lambda_ethereum_consensus/validator/utils.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  lib/libp2p_port.ex
Labels: bug

#865 fix: was returning a list instead of the subnet ID
  lib/lambda_ethereum_consensus/validator/validator.ex
Labels: bug

#864 feat: add `engine_newPayloadV3` to `EngineApi`
  config/runtime.exs
  lib/lambda_ethereum_consensus/execution/auth.ex
  lib/lambda_ethereum_consensus/execution/engine_api.ex
  lib/lambda_ethereum_consensus/execution/engine_api/api.ex
  lib/lambda_ethereum_consensus/execution/engine_api/mocked.ex
  lib/lambda_ethereum_consensus/execution/execution_client.ex
Labels: deneb

#873 feat: download blobs in `PendingBlocks`
  lib/lambda_ethereum_consensus/beacon/pending_blocks.ex
Labels: deneb

#883 docs: update consolidated specs with Deneb changes
  docs/specs/beacon-chain.md
  docs/specs/fork-choice.md
  docs/specs/fork.md
  docs/specs/p2p-interface.md
  docs/specs/validator.md
Labels: documentation, deneb

#898 ci: update spectest vectors cache path
  .github/workflows/ci.yml
Labels: bug, P0

#890 feat: collect attestations during slot
  lib/lambda_ethereum_consensus/beacon/beacon_node.ex
  lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
Labels: validator, Aggregators

#894 feat: document `SszEx.schema`
  lib/container.ex
  lib/ssz_ex.ex
Labels: documentation

#892 feat: construct and publish aggregated attestations
  lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  lib/utils/bit_field.ex
Labels: validator, Aggregators

#897 feat: load validator keys from file (prototype)
  config/runtime.exs
  lib/lambda_ethereum_consensus/validator/validator.ex
Labels: validator

#919 docs: remove broken links and update references to proof of work.
  docs/specs/beacon-chain.md
  docs/specs/deposit-contract.md
  docs/specs/fork-choice.md
  docs/specs/p2p-interface.md
  docs/specs/validator.md
  native/ssz_nif/README.md
Labels: documentation

#922 chore: bump Elixir version
  .github/workflows/ci.yml
  .tool-versions
Labels: elixir

#909 feat: validator proposal duties lookahead
  lib/lambda_ethereum_consensus/p2p/gossip/attestation.ex
  lib/lambda_ethereum_consensus/state_transition/accessors.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  native/libp2p_port/internal/subscriptions/subscriptions.go
  test/unit/libp2p_port_test.exs
Labels: validator, Proposer

#920 feat: collect `BLSToExecutionChange` from gossip
  lib/lambda_ethereum_consensus/fork_choice/fork_choice.ex
  lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex
  lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
  lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
Labels: validator, Proposer

#927 feat: collect slashings and voluntary exits
  lib/lambda_ethereum_consensus/p2p/gossip/gossipsub.ex
  lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
  lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
Labels: validator, Proposer

#932 feat: collect attestations
  lib/lambda_ethereum_consensus/p2p/gossip/handler.ex
  lib/lambda_ethereum_consensus/p2p/gossip/operations_collector.ex
Labels: validator, Proposer

#934 refactor: simplify `ZeroHashes`
  lib/ssz_ex.ex
  lib/utils/zero_hashes.ex
Labels: Refactor

#936 feat: initialize pruned deposit tree on start
  lib/lambda_ethereum_consensus/beacon/beacon_node.ex
  lib/lambda_ethereum_consensus/beacon/checkpoint_sync.ex
  lib/lambda_ethereum_consensus/state_transition/predicates.ex
  lib/ssz_ex.ex
  lib/types/deposit_tree.ex
  lib/types/deposit_tree_snapshot.ex
  lib/types/store.ex
  test/unit/deposit_tree_test.exs
Labels: validator, Proposer

#939 feat: add operations to block
  lib/lambda_ethereum_consensus/validator/block_request.ex
  lib/lambda_ethereum_consensus/validator/proposer.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  lib/types/beacon_chain/beacon_block_body.ex
  test/unit/validator/proposer_test.exs
Labels: validator, Proposer

#944 feat: compute `parent_root` and trivial `eth1_data`
  lib/lambda_ethereum_consensus/validator/block_request.ex
  lib/lambda_ethereum_consensus/validator/proposer.ex
  lib/lambda_ethereum_consensus/validator/validator.ex
  test/unit/validator/proposer_test.exs
Labels: validator, Proposer
